In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
file_path = '36151-0001-Data.dta'

df = pd.read_stata(file_path)

# print(df.head())

In [3]:
# Split the dataset based on a specific column (replace 'column_name' with the column you want to split on)
column_name = 'STATEID'
unique_values = df[column_name].unique()

output_dir = "states_datasets"
os.makedirs(output_dir, exist_ok=True)

# Save each subset as a separate CSV file
for value in unique_values:
    file_name = f"{output_dir}/data_subset_{value}.csv"
    df[df[column_name] == value].to_csv(file_name, index=False)
    print(f"Saved: {file_name}")

# Save full dataset as well
# df.to_csv(f"./data_subset_India_00.csv", index=False)
# print(f"Saved: ./data_subset_India_00.csv")

Saved: states_datasets/data_subset_Jammu & Kashmir 01.csv
Saved: states_datasets/data_subset_Himachal Pradesh 02.csv
Saved: states_datasets/data_subset_Punjab 03.csv
Saved: states_datasets/data_subset_Chandigarh 04.csv
Saved: states_datasets/data_subset_Uttarakhand 05.csv
Saved: states_datasets/data_subset_Haryana 06.csv
Saved: states_datasets/data_subset_Delhi 07.csv
Saved: states_datasets/data_subset_Rajasthan 08.csv
Saved: states_datasets/data_subset_Uttar Pradesh 09.csv
Saved: states_datasets/data_subset_Bihar 10.csv
Saved: states_datasets/data_subset_Sikkim 11.csv
Saved: states_datasets/data_subset_Arunachal Pradesh 12.csv
Saved: states_datasets/data_subset_Nagaland 13.csv
Saved: states_datasets/data_subset_Manipur 14.csv
Saved: states_datasets/data_subset_Mizoram 15.csv
Saved: states_datasets/data_subset_Tripura 16.csv
Saved: states_datasets/data_subset_Meghalaya 17.csv
Saved: states_datasets/data_subset_Assam 18.csv
Saved: states_datasets/data_subset_West Bengal 19.csv
Saved: states_datasets/data_subset_Jharkhand 20.csv
Saved: states_datasets/data_subset_Orissa 21.csv
Saved: states_datasets/data_subset_Chhattisgarh 22.csv
Saved: states_datasets/data_subset_Madhya Pradesh 23.csv
Saved: states_datasets/data_subset_Gujarat 24.csv
Saved: states_datasets/data_subset_Daman & Diu 25.csv
Saved: states_datasets/data_subset_Dadra+Nagar Haveli 26.csv
Saved: states_datasets/data_subset_Maharashtra 27.csv
Saved: states_datasets/data_subset_Andhra Pradesh 28.csv
Saved: states_datasets/data_subset_Karnataka 29.csv
Saved: states_datasets/data_subset_Goa 30.csv
Saved: states_datasets/data_subset_Kerala 32.csv
Saved: states_datasets/data_subset_Tamil Nadu 33.csv
Saved: states_datasets/data_subset_Pondicherry 34.csv

In [ ]:
ame = 'STATEID'
unique_values = df[column_name].unique()

# Create separate DataFrames for each unique value in the column and store them in variables
datasets = {}
for value in unique_values:
    var_name = f'data_subset_{value}'
    datasets[var_name] = df[df[column_name] == value]
    # print(f'Created variable: {var_name}')
datasets["data_subset_India 00"] = df

In [4]:
Basic_info_list = ["RO3", "RO4", "RO5", "RO6", "RO7", "RO8", "RO9", "RO10"]

Farm = ["FM1", "FM36Y", "FM37", "FM38", "FMHOURS", "WKFARM", "FM39AY"]

Animal_work = ["AN1", "AN5Y", "AN6", "AN7Y"]

Non_farm = ["NF1", "NFBN1", "NF9", "NF12", "NF13", "NF15Y", "NFBN21", "NF29", "NF32", "NF33", "NF35Y", "NFBN41", "NF49", "NF52", "NF53", "NFDAYS", "NFHOURS", "NF55Y"]

Income = ["IN11S1", "IN13S1", "IN11S2", "IN13S2", "IN11S3", "IN13S3", "IN11S4", "IN13S4", "IN11S5", "IN13S5", "IN11S6", "IN13S6", "IN11S7",
           "IN13S7", "IN11S8", "IN13S8", "IN18", "IN19", "IN20", "IN21", "IN22", "IN23", "IN24"]

Education = ["ED2", "ED3", "ED4", "ED5", "ED6", "EDUC7", "EDUNDER1", "ED7", "ED8", "ED9", "ED10", "ED11", "ED12", "ED13"]

Technology = ["MM7Y", "MM8", "MM9", "MM12Y", "MM13", "MM14"]

Teacher_and_school = ["TA3", "TA4", "TA5", "TA6", "TA8A", "TA8B", "TA9A", "TA9B", "TA10A", "TA10B"]

College_school = ["CS3", "CS3Y", "CS4", "CS5", "CS6", "CS7", "CS8", "CS9", "CS10", "CS11", "CS12", "CS13", "CS16", "CS17",
                   "CS18", "CS19", "CS20", "CS21", "CS22", "CS23", "CS24", "CS25", "CS26", "CS27", "CS28"]

Child_and_school = ["CH2", "CH3", "CH4A", "CH4B", "CH5", "CH6", "CH7", "CH8", "CH9", "CH10", "CH11", "CH12", "CH13", "CH14", "CH15", "CH16", "CH17", "CH18", "CH19", "CH20", "CH22"]

Short_term_Morbidity = ["SM3", "SM4", "SM5", "SM6", "SM7", "SM8", "SM9", "SM10", "SM11", "SM12", "SM14A", "SM14B", "SM15A", "SM15B", "SM16", "SM17", "SM18", "SM19", "SM20", "SM21", "SM22"]

Major_Morbidity =["MB3", "MB4", "MB5", "MB6", "MB7", "MB8", "MB9", "MB10", "MB11", "MB12", "MB13", "MB14", "MB15", "MB16", "MB17", 
                  "MB18", "MB19", "MB21A", "MB21B", "MB22A", "MB22B", "MB23", "MB24", "MB25", "MB26", "MB27", "MB28", "MB29"]

Activity_difficulty = ["AD3", "AD4", "AD5", "AD6", "AD7", "AD8", "AD9"]

Tobacco_and_other = ["TO3", "TO4", "TO5", "TO6"]

Anthropometry = ["AP2", "AP3", "AP5", "AP6", "AP7", "AP8", "AP9"]

Eligible_women = ["EW3Y"]

Urban = ["URBAN2011", "URBAN4_2011", "METRO", "METRO6", "POVLINE2005", "POVLINE2012","DEFLATOR"]

Household_details = ["NPERSONS", "EWELIGIBLE", "EWQELIGIBLE","MHEADAGE", "FHEADAGE", "NADULTM", "NADULTF", "NCHILDM", "NCHILDF", "NTEENM", "NTEENF", "NELDERM", "NELDERF", "NMARRIEDM", 
                     "NMARRIEDF", "NWKNONAG", "NWKAGLAB", "NWKSALARY", "NWKBUSINESS", "NWKFARM", "NWKANIMAL", "NWKNREGA", "NWKNREGA4", "NWKNONNREGA", "NWKANY5",
                     "NNR", "HHEDUC", "HHEDUCM", "HHEDUCF"]

Caste_and_Religion = ["ID11", "ID13", "GROUPS"]

Buiseness = ["NF5", "NF25", "NF45"]

Household_financial = ["COTOTAL", "COPC", "ASSETS", "ASSETS2005", "INCCROP", "INCAGPROP", "INCANIMAL", "INCAG", "INCBUS", "INCOTHER", "INCEARN", "INCBENEFITS", "INCREMIT", "INCOME", "INCOMEPC","RSUNEARN"]

Work_participation = ["WKANIMAL", "WKBUSINESS","WKNREGA", "WKDAYS", "WKHOURS", "WKANY5"]

WorkSpace = ["WS3NM", "WS4", "WS5", "WS7", "WS7MONTHS", "WS8", "WS8YEAR", "WS9", "WS10", "WS10ANNUAL", "WSEARN", "WSEARNHOURLY", "WS11", "WS11MEALS", "WS11HOUSE",
              "WS11MEALSRS", "WS11HOUSERS", "WS12", "WS13", "WS14", "WS15", "WS7AGLAB", "WS8AGLAB", "WSEARNAGLAB", "WKAGLAB", "WS7NONAG", "WS8NONAG", "WSEARNNONAG",
                "WKNONAG", "WS7SALARY", "WS8SALARY", "WSEARNSALARY", "WKSALARY", "WS7NREGA", "WS8NREGA", "WSEARNNREGA"]

Income_Household = ["INCNONAG", "INCAGLAB", "INCSALARY", "INCNREGA", "INCNONNREGA"]

Migrants_data = ["MG4", "MG5", "MG6", "MG7", "MG8", "MG9NM", "MG10", "MG11","MGYEAR5", "NMIG5", "MGMONTHS5", "MGYEAR1", "NMIG1", "MGMONTHS1"]

In [5]:
def plot_data(df, combined_list, p):
    for element in combined_list:
        if element in df.columns:
            # Convert to numeric and drop NaN values
            df[element] = pd.to_numeric(df[element], errors='coerce')
            df[element].dropna(inplace=True)  # Or handle NaN as needed
            
            if not df[element].empty:  # Check if the series is not empty
                plt.figure(figsize=(20, 10))
                df[element].plot(kind='line', marker='o')
                plt.title(f"Data for {element} in {p}")
                plt.xlabel("Index")  # Modify as needed
                plt.ylabel(f"{element} Values")  # Modify as needed
                plt.grid(True)
                
                # Save the plot as an image file
                plt.savefig(f"{p}/{element}_graph.png")
                plt.close()
            else:
                print(f"No numeric data available for {element} in DataFrame")
        else:
            print(f"Column {element} not found in DataFrame")

In [7]:
element_for_state = {}
for d in datasets:
    element_for_state[d] = {}
    for e in list:
        element_for_state[d][e] = df[e]
        element_for_state[d][e].dropna(inplace=True)